// macros for controling the debugging process

#ifndef TRUE
#define TRUE 1
#endif

#ifndef FALSE
#define FALSE 0
#endif


// Exception handling control
#ifndef LOL_BLOCKS_EXCEPTIONS_ENABLED
#define LOL_BLOCKS_EXCEPTIONS_ENABLED TRUE
#endif

#ifdef LOL_BLOCKS_EXCEPTIONS_SWITCH

#endif


#ifdef DEBUG
#ifndef LOL_BLOCKS_GENERAL_DEBUGGING_ENABLED
#define LOL_BLOCKS_GENERAL_DEBUGGING_ENABLED TRUE
#endif // #ifndef LOL_BLOCKS_GENERAL_DEBUGGING_ENABLED
#endif // #ifdef DEBUG

#ifdef LOL_BLOCKS_GENERAL_DEBUGGING_ENABLED
#define LOL_BLOCKS_DX12_DEBUGGING_ENABLED TRUE
#define LOL_BLOCKS_LOGGING_SYSTEM_DEBUGGING_ENABLED TRUE
#define LOL_BLOCKS_MEMORY_MANAGER_DEBUGGING_ENABLED TRUE
#endif





#ifdef TRUE
#undef TRUE
#endif

#ifdef FALSE
#undef FALSE
#endif